config/routes.rb
Rails.application.routes.draw do
  resources :blocks
  resources :users
  get 'signup' => 'users#new'
  root 'blocks#index'

  get '/collection' => 'blocks#collection'

  get     'login' => 'sessions#new'
  post    'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/block.rb
class Block < ActiveRecord::Base

  mount_uploader :pic, PicUploader

  validates :name,
    presence: { message: "入力してください" },
    length: { minimum: 3, message: "短すぎ！" }
  validates :memo, presence: true

  belongs_to :user

  acts_as_taggable

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :blocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController

  before_action :set_block, only: [:show, :edit, :update, :destroy]

  def index
    @blocks = Block.all
  end

  def collection
    if params[:q].blank?
      @blocks = Block.all
    else
      aaa = params[:q]
      logger.debug aaa.inspect
      @blocks = Block.tagged_with( aaa )
    end
  end

  def show
  end

  def new
    @block = Block.new
  end

  def create
    @block = Block.new(block_params)
    nm = Natto::MeCab.new("-d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/")
    nm.parse(@block.name) do |n|
      @block.tag_list.add(n.surface.to_s)
    end
    if logged_in?
      @block.user_id = session[:user_id]
    end
    if @block.save
      redirect_to blocks_path
    else
      render 'new'
    end
  end

  def edit
  end
 
  def update
    if @block.update(block_params)
      nm = Natto::MeCab.new("-d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/")
      nm.parse(@block.name) do |n|
        @block.tag_list.add(n.surface.to_s)
      end
      @block.save
#      logger.debug '---------------------------------------'
#      logger.debug @block.tag_list.inspect
#      logger.debug '---------------------------------------'
      redirect_to blocks_path
    else
      render 'edit'
    end
  end

  def destroy
    @block.destroy
    redirect_to blocks_path
  end

  private def block_params
    params[:block].permit(:name, :memo, :pic, :pic_cache, :tag_list) 
  end

  def set_block
    @block = Block.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @userblocks = Block.where(user_id: @user)

    logger.fatal "------------------"
    logger.debug @userblocks.inspect
    logger.fatal "------------------"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end
 
  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private def user_params
    params[:user].permit(:name, :email, :password, :password_confirmation) 
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blocks/_form.html.erb
<%= form_for @block do |f| %>
  <p>
    <%= f.label :name %> <%= f.text_field :name %> <br />
    <% if @block.errors.any? %>
      <%= @block.errors.messages[:name][0] %>
    <% end %>

    <%= f.label :tag_list %> <%= f.text_field :tag_list %> <br />
    <% if @block.errors.any? %>
      <%= @block.errors.messages[:tag_list][0] %>
    <% end %>

    <%= f.label :memo %> <%= f.text_field :memo %> <br />
    <% if @block.errors.any? %>
      <%= @block.errors.messages[:memo][0] %>
    <% end %>

    <% if @block.pic? %>
        <%= image_tag @block.pic.url %>
    <% end %>
    <%= f.file_field :pic %>
    <%= f.hidden_field :pic_cache %>

  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    --- for debug ------------------------<br />
    <%= @block.inspect %><br />
    <%= @block.errors.inspect %><br />
    -------------------------------------------<br />
  </p>
<% end %>

app/views/blocks/index.html.erb
<h1>Blocks</h1>

<ul>
  <% @blocks.each do |block| %>
    <li>
      <%= link_to block.name, block_path(block.id) %>
      <%= link_to "[edit]", edit_block_path(block.id) %>
      <%= link_to "[del]", block_path(block.id), method: :delete, data: { confirm: "are you sure?" } %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_block_path %></p>
<p><%= link_to "Collection Page", collection_path %></p>

app/views/blocks/show.html.erb
<h1><%= @block.name %></h1>

<div>
  <ul>
    <li><%= @block.memo %></li>
    <li><%= @block.tag_list %></li>
    <li><%= @block.user_id %></li>
  </ul>

  <% if @block.pic? %>
    <div>
      <%= image_tag @block.pic.url %>
    </div>
  <% end %> 
 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">
  <div id="section-data" class="col-xs-12 col-md-9">
    <%= image_tag "logo.png" %>
  </div>

  <div id="section-history" class="col-xs-12 col-md-3">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if logged_in? %>
        <li><%= link_to "My Page", current_user %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </div>

</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %> <%= f.text_field :name %> <br />
    <% if @user.errors.any? %>
      <%= @user.errors.messages[:name][0] %>
    <% end %>
    <%= f.label :email %> <%= f.text_field :email %> <br />
    <% if @user.errors.any? %>
      <%= @user.errors.messages[:email][0] %>
    <% end %>
    <%= f.label :password %> <%= f.text_field :password %> <br />
    <% if @user.errors.any? %>
      <%= @user.errors.messages[:password][0] %>
    <% end %>
    <%= f.label :password_confirmation %> <%= f.text_field :password_confirmation %> <br />
    <% if @user.errors.any? %>
      <%= @user.errors.messages[:password_confirmation][0] %>
    <% end %>

  </p>
  <p>
    <%= f.submit %>
  </p>
    --- for debug ------------------------<br />
    <%= @user.inspect %><br />
    <%= @user.errors.inspect %><br />
    -------------------------------------------<br />
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user.id) %>
      <%= link_to "[edit]", edit_user_path(user.id) %>
      <%= link_to "[del]", user_path(user.id), method: :delete, data: { confirm: "are you sure?" } %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_user_path %></p>

app/views/users/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div>
  <%= @user.email %>
  <%= @user.password_digest %>

  <ul>
    <% @userblocks.each do |block| %>
      <li>
        <%= link_to block.name, block_path(block.id) %>
        <%= link_to "[edit]", edit_block_path(block.id) %>
        <%= link_to "[del]", block_path(block.id), method: :delete, data: { confirm: "are you sure?" } %>
      </li>
    <% end %>
  </ul>

</div>